from fastapi import FastAPI, Depends, Query, HTTPException
from sqlalchemy.orm import Session
from .database import get_db, Base, engine
from .schemas import SearchResponse, ProductSchema, ChatHistoryResponse
from .repositories import ECommerceRepository
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="E-Commerce AI System Gateway")

import json

@app.get("/api/health")
def health_check():
    """
    Health check endpoint to verify the backend is running properly.
    Returns a simple status JSON.
    """
    return {"status": "healthy"}

@app.get("/api/chat/{session_id}", response_model=ChatHistoryResponse)
def get_chat_history(session_id: str, db: Session = Depends(get_db)):
    """
    Retrieves the chat history for a given session ID.
    Parses agent messages to hydrate product IDs into rich product objects.
    """
    try:
        repo = ECommerceRepository(db)
        history = repo.get_chat_history(session_id)
        history_out = []
        for msg in history:
            if msg["role"] == "agent":
                try:
                    parsed = json.loads(msg["message"])
                    text = parsed.get("text", msg["message"])
                    p_ids = parsed.get("product_ids", [])
                    products = repo.fetch_product_by_ids(p_ids) if p_ids else []
                    history_out.append({"role": "agent", "message": text, "products": products})
                except Exception:
                    history_out.append({"role": "agent", "message": msg["message"], "products": []})
            else:
                history_out.append({"role": "user", "message": msg["message"]})
                
        return ChatHistoryResponse(
            session_id=session_id,
            history=history_out
        )
    except Exception as e:
        logger.error(f"Error fetching chat history: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")

@app.get("/api/search", response_model=SearchResponse)
def search(query: str = Query(...), session_id: str = Query(...), db: Session = Depends(get_db)):
    """
    Processes a user search query, logs it, generates an AI response,
    fetches relevant products, logs the agent's response, and returns the result.
    """
    try:
        repo = ECommerceRepository(db)
        
        repo.add_chat_message(session_id=session_id, role="user", message=query)
        
        ai_response_text = "This is a placeholder AI response. In Phase 2, this will be generated by the RAG Engine and vLLM."
        
        products = repo.fetch_product_list(limit=5)
        product_ids = [p["id"] for p in products]
        
        agent_db_msg = json.dumps({"text": ai_response_text, "product_ids": product_ids})
        repo.add_chat_message(session_id=session_id, role="agent", message=agent_db_msg)
        
        return SearchResponse(
            ai_response=ai_response_text,
            products=products
        )
    except Exception as e:
        logger.error(f"Error processing search: {e}")
        raise HTTPException(status_code=500, detail="Internal server error")
